### ISSUE TITLE
[Bug]: Molecules calc types still trying to import missing enums

### ISSUE THREAD

**Issue by tsmathis** [materialsproject/emmet#1089]
### What happened?

qchem enums file got removed in #926. They are still getting imported here: [init](https://github.com/materialsproject/emmet/blob/69adac598d0cc20638ab5408f7dade15fb0c3832/emmet-core/emmet/core/qchem/calc_types/__init__.py#L8)

@espottesmith, were they supposed to be removed?

### Version

v0.84.2rc7

### Which OS?

- [ ] MacOS
- [ ] Windows
- [ ] Linux

**Comment by tsmathis** [comment]
@tschaume, this regression should also put a hold on a full release

**Comment by tsmathis** [comment]
direct link to the diff in #926, [link](https://github.com/materialsproject/emmet/pull/926/files#diff-9426ec43e6768f5ee9c8ffe7e76b3e95131d1b25bc6f307630e9a9c4f8db0b47)

**Comment by tsmathis** [comment]
see #1092 for PR that would add these back, still waiting for input though

**Comment by espottesmith** [comment]
Sorry I'm coming in late to this.

It doesn't really matter if they're included or not. If they're not, they'll be auto-generated upon import. In my mind, it makes sense not to have them included, because if you've made a change to the allowed levels of theory, calculation types, etc., the enums will only be regenerated if you first delete them and then let them regenerate. Not having the enums file present by default seems to potentially save a step.

**Comment by tsmathis** [comment]
Okay no problem, I overlooked the autogenerate behavior. I was having some import errors with the latest rc following the removal of the enums of version control, but that could be a misconfigured environment on my end.

Thanks for weighing in!
